# Generated by Django 4.2.22 on 2025-06-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebsiteData",
            fields=[
                (
                    "website",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("website_url", models.URLField()),
                ("website_author", models.CharField(max_length=100)),
            ],
        ),
    ]
