# Generated by Django 4.2.22 on 2025-06-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitedata",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="websitedata",
            name="website",
            field=models.CharField(max_length=100),
        ),
    ]
