name: Django CI/CD

on:
  push:
    branches: ["*"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Black (formatter check)
      run: black --check .

    - name: Run Flake8 (linting)
      run: flake8 .

    - name: Run isort (import order checker)
      run: isort . --check-only

    - name: Run Bandit (security scan)
      run: bandit -r .

    - name: Run Pip Audit (dependency scan)
      run: pip-audit

    - name: Run Mypy (type checking)
      run: mypy .

    - name: Run Django checks
      run: |
        cd website_genarator
        python manage.py check

    - name: Run Tests (placeholder)
      run: echo 'Here you would run --> python manage.py test'
